services:
  app:
    build: 
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_played_tracks
